// Generated by CoffeeScript 1.3.3
(function() {
  var AppViewModel, ko, randomString, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  randomString = function(n) {
    var chars, i;
    if (n == null) {
      n = 8;
    }
    chars = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXTZabcdefghiklmnopqrstuvwxyz';
    return ((function() {
      var _i, _results;
      _results = [];
      for (i = _i = 1; 1 <= n ? _i <= n : _i >= n; i = 1 <= n ? ++_i : --_i) {
        _results.push(chars.charAt(Math.floor(Math.random() * chars.length)));
      }
      return _results;
    })()).join('');
  };

  ko = root.ko;

  AppViewModel = function() {
    this.result = ko.observable(randomString(6));
    this.generate = function() {
      this.result(randomString(6));
    };
  };

  ko.applyBindings(new AppViewModel());

}).call(this);
